import { FileText, Filter, Search, SlidersHorizontal, Tag, Sparkles, Trash2, FolderOpen, Undo2, Redo2, Plus, PanelRight, MoreHorizontal } from "lucide-react"
import { NoteGenAppShell } from "@/components/notegen/app-shell-replica"
import { NoteGenWorkspaceSidebar } from "@/components/notegen/workspace-switcher"
import { NoteGenChatEmpty } from "@/components/notegen/chat-empty-replica"
import { NoteGenTagPlusIcon } from "@/components/notegen/tag-plus-icon"
import { skillWorkspaceCss } from "@/components/notegen/skill-agent-replica"
import type { NoteGenReplicaLanguage } from "@/components/notegen/types"

/** Natural-size record scene for MCP tutorials; all contents supplied by the caller. */
export function NoteGenMcpRecordWorkspace({ title, content, tag, time, lang = "cn" }: { title: string; content: string; tag: string; time: string; lang?: NoteGenReplicaLanguage }) {
  const en = lang === "en"
  return <div className="ng-skill-workspace replica ng-mcp-record-workspace" data-icon-animation="timeline"><style>{skillWorkspaceCss + mcpRecordCss}</style><NoteGenAppShell lang={lang} workspace="records" className="ng-skill-shell" titleBarProps={{showShortcutHints:false}} statusBarProps={{workspaceName:en?"Default workspace":"默认工作区"}}><div className="ng-skill-layout">
    <NoteGenWorkspaceSidebar lang={lang} value="records"><div className="ng-mcp-record-search"><Search size={14} /><span>{en?"Search records":"搜索记录"}</span><NoteGenTagPlusIcon size={16} /><Filter size={16} /><SlidersHorizontal size={16} /></div><div className="ng-mcp-record-tags"><div><Tag size={14} />{en?"All records":"全部记录"}<small>1</small></div><div className="ng-mcp-record-tag-active"><Tag size={14} />{tag}<small>1</small></div></div><div className="ng-mcp-record-date">{en?"Today":"今天"}</div><article className="ng-mcp-record-item"><div><span><FileText size={12} />{en?"Text":"文本"}</span><small>{en?"Just now":"刚刚"}</small></div><strong>{title}</strong><p>{content}</p><b>{tag}</b></article></NoteGenWorkspaceSidebar>
    <section className="ng-skill-editor"><div className="ng-skill-tabs"><Undo2 size={16}/><Redo2 size={16}/><div className="ng-skill-active-tab"><FileText size={14}/><span>{title}</span></div><Plus size={16}/><PanelRight size={16}/><MoreHorizontal size={16}/></div><header className="ng-mcp-record-head"><FileText size={34}/><div><p><b>{en?"Text":"文本"}</b><time>{time}</time></p><span>{title}</span></div><div className="ng-mcp-record-actions"><Tag size={16}/><FolderOpen size={16}/><Sparkles size={16}/><Trash2 size={16}/></div></header><div className="ng-mcp-record-content"><span>{en?"Content":"内容"}</span><p>{content}</p></div></section>
    <section className="ng-skill-agent"><header><span>{en?"Conversations (0)":"历史对话 (0)"}</span><MoreHorizontal size={16}/></header><div className="ng-mcp-record-chat"><NoteGenChatEmpty lang={lang} recentConversations={[]} /></div><footer className="ng-mcp-record-composer"><p>{en?"Ask a question or organize records into an article…":"你可以提问或将记录整理为文章..."}</p><small>{en?"Confirm before edits":"修改前确认"}</small></footer></section>
  </div></NoteGenAppShell></div>
}
export const mcpRecordCss = `
.ng-mcp-record-workspace{background:hsl(var(--ng-skill-background));color:hsl(var(--ng-skill-foreground))}.ng-mcp-record-search{display:flex;align-items:center;gap:8px;height:40px;border-bottom:1px solid hsl(var(--ng-skill-border));padding:0 10px;color:hsl(var(--ng-skill-muted-foreground));font-size:14px}.ng-mcp-record-search span{flex:1}.ng-mcp-record-tags{padding:12px 10px}.ng-mcp-record-tags>div{display:flex;align-items:center;gap:8px;padding:6px 8px;font-size:14px;border-radius:6px}.ng-mcp-record-tags small{margin-left:auto;color:hsl(var(--ng-skill-muted-foreground))}.ng-mcp-record-tag-active{background:hsl(var(--ng-skill-muted))}.ng-mcp-record-date{font-size:12px;color:hsl(var(--ng-skill-muted-foreground));padding:8px 12px}.ng-mcp-record-item{border-top:1px solid hsl(var(--ng-skill-border));border-bottom:1px solid hsl(var(--ng-skill-border));background:hsl(var(--ng-skill-muted)/.5);padding:10px 12px;font-size:14px}.ng-mcp-record-item>div{display:flex;align-items:center;justify-content:space-between;color:hsl(var(--ng-skill-muted-foreground));font-size:12px;margin-bottom:6px}.ng-mcp-record-item>div span{display:flex;align-items:center;gap:4px;border:1px solid hsl(var(--ng-skill-border));border-radius:4px;padding:0 5px}.ng-mcp-record-item strong{font-weight:500}.ng-mcp-record-item p{font-size:12px;color:hsl(var(--ng-skill-muted-foreground));margin:4px 0;display:-webkit-box;-webkit-line-clamp:2;-webkit-box-orient:vertical;overflow:hidden}.ng-mcp-record-item b{display:inline-block;background:hsl(var(--ng-skill-muted));font-weight:400;padding:0 6px;border-radius:4px;font-size:11px;margin-top:4px}.ng-mcp-record-head{display:flex;align-items:center;gap:16px;padding:16px 20px;border-bottom:1px solid hsl(var(--ng-skill-border))}.ng-mcp-record-head>svg{color:hsl(var(--ng-skill-muted-foreground))}.ng-mcp-record-head>div:first-of-type{flex:1;min-width:0}.ng-mcp-record-head p{display:flex;align-items:center;gap:12px;margin:0 0 6px;font-size:12px;color:hsl(var(--ng-skill-muted-foreground))}.ng-mcp-record-head b{font-weight:400;border:1px solid hsl(var(--ng-skill-border));border-radius:4px;padding:0 8px}.ng-mcp-record-head span{font-size:14px;color:hsl(var(--ng-skill-muted-foreground))}.ng-mcp-record-actions{display:flex;gap:16px;color:hsl(var(--ng-skill-muted-foreground))}.ng-mcp-record-content{padding:20px}.ng-mcp-record-content>span{color:hsl(var(--ng-skill-muted-foreground));font-size:14px}.ng-mcp-record-content p{font-size:16px;line-height:1.9;white-space:pre-wrap;margin:18px 0}.ng-mcp-record-chat{flex:1;position:relative;min-height:0}.ng-mcp-record-composer{border:1px solid hsl(var(--ng-skill-border));border-radius:12px;margin:4px;padding:12px;color:hsl(var(--ng-skill-muted-foreground));font-size:14px}.ng-mcp-record-composer p{margin:0 0 24px}.ng-mcp-record-composer small{font-size:12px}
`
