import type { ReactNode } from "react"
import { BookOpen, Bot, Brain, CalendarDays, CheckSquare, ChevronDown, ChevronLeft, ChevronRight, Cloud, DatabaseBackup, Drama, EllipsisVertical, FileCog, FilePlus2, FileText, Filter, FolderOpen, Globe2, Highlighter, History, Image, ImageUp, LayoutList, LayoutTemplate, MessageSquare, MessageSquareDashed, MessageSquarePlus, Mic, Palette, PenTool, Plus, Puzzle, RefreshCw, ScanText, Search, SearchCode, Send, Settings, Sparkles, SquarePen, Trash2, User, Volume2 } from "lucide-react"

import type { NoteGenReplicaLanguage } from "@/components/notegen/types"
import { cn } from "@/lib/utils"

export type NoteGenMobileScreen = "capture" | "chat" | "writing" | "canvas" | "settings"

export function NoteGenMobileFrame({ children, className }: { children: ReactNode; className?: string }) {
  return <div className={cn("relative mx-auto aspect-[9/19.5] w-full max-w-[270px] overflow-hidden rounded-[2.2rem] border-[5px] border-foreground bg-background text-[9px] shadow-2xl", className)}><div className="absolute left-1/2 top-1.5 z-20 h-4 w-20 -translate-x-1/2 rounded-full bg-foreground" />{children}</div>
}

export function NoteGenMobileStatusBar() {
  return <div className="flex h-7 items-center justify-between px-5 pt-1 text-[8px] font-medium"><span>9:41</span><span>● ◒ ▰</span></div>
}

export function NoteGenMobileHeader({ title, trailing }: { title: string; trailing?: ReactNode }) {
  return <header className="flex h-11 items-center border-b px-4"><h2 className="text-sm font-semibold">{title}</h2><div className="ml-auto flex items-center gap-3 text-muted-foreground">{trailing ?? <Search className="size-4" />}</div></header>
}

export function NoteGenMobileDock({ screen = "capture", lang = "cn" }: { screen?: NoteGenMobileScreen; lang?: NoteGenReplicaLanguage }) {
  const activeScreen = screen === "settings" ? "chat" : screen
  const items = [{ id: "chat", icon: MessageSquare, label: lang === "en" ? "Chat" : "对话" }, { id: "writing", icon: SquarePen, label: lang === "en" ? "Write" : "写作" }, { id: "quick", icon: Plus, label: lang === "en" ? "Record" : "快记" }, { id: "capture", icon: Highlighter, label: lang === "en" ? "Records" : "记录" }, { id: "canvas", icon: Palette, label: lang === "en" ? "Canvas" : "画布" }]
  return <nav className="grid h-14 grid-cols-5 border-t bg-background/95 px-1 pb-1">{items.map((item) => { const active = activeScreen === item.id; return <div key={item.id} className={cn("flex flex-col items-center justify-center gap-0.5 text-[7px] text-muted-foreground", active && "text-foreground")}><span className={cn("flex size-6 items-center justify-center rounded-full", item.id === "quick" && "bg-foreground text-background")}><item.icon className="size-4" strokeWidth={active ? 2.2 : 1.7} /></span>{item.label}</div> })}</nav>
}

export function NoteGenMobileCapture({ lang = "cn" }: { lang?: NoteGenReplicaLanguage }) {
  return <div className="flex min-h-0 flex-1 flex-col"><header className="flex h-11 items-center border-b px-2"><span className="flex size-8 items-center justify-center rounded-full bg-muted"><User className="size-4" /></span><span className="ml-1 flex items-center gap-1 px-2 text-[10px] font-medium">{lang === "en" ? "All records" : "全部记录"}<ChevronDown className="size-3" /></span><div className="ml-auto flex items-center gap-3 text-muted-foreground"><Filter className="size-4" /><CheckSquare className="size-4" /><Trash2 className="size-4" /></div></header><div className="min-h-0 flex-1 overflow-hidden px-3 py-2"><p className="mb-2 text-[8px] font-medium text-muted-foreground">{lang === "en" ? "TODAY" : "今天"}</p><div className="flex flex-col gap-2"><article className="rounded-xl border bg-card p-3 shadow-xs"><div className="flex items-center gap-2"><span className="rounded bg-muted px-1.5 py-0.5 text-[7px]">{lang === "en" ? "Text" : "文本"}</span><span className="ml-auto text-[7px] text-muted-foreground">10:24</span></div><p className="mt-2 text-[9px] leading-4">{lang === "en" ? "Capture first and organize only when needed." : "先记录，只在需要时整理。"}</p></article><article className="rounded-xl border bg-card p-3"><div className="flex items-center gap-2"><span className="rounded bg-muted px-1.5 py-0.5 text-[7px]">{lang === "en" ? "Recording" : "录音"}</span><span className="ml-auto text-[7px] text-muted-foreground">09:48</span></div><p className="mt-2 text-[9px]">{lang === "en" ? "Product meeting memo · 01:42" : "产品会议速记 · 01:42"}</p></article><article className="rounded-xl border bg-card p-3"><div className="flex items-center gap-2"><span className="rounded bg-muted px-1.5 py-0.5 text-[7px]">{lang === "en" ? "Image" : "图片"}</span><span className="ml-auto text-[7px] text-muted-foreground">{lang === "en" ? "Yesterday" : "昨天"}</span></div><p className="mt-2 text-[9px]">{lang === "en" ? "Interface references" : "界面参考"}</p></article></div></div></div>
}

export function NoteGenMobileChat({ lang = "cn" }: { lang?: NoteGenReplicaLanguage }) {
  return <div className="flex min-h-0 flex-1 flex-col"><header className="flex h-11 items-center border-b px-2"><span className="flex size-8 items-center justify-center rounded-full bg-muted"><User className="size-4" /></span><div className="ml-auto flex items-center gap-3 text-muted-foreground"><Search className="size-4" /><History className="size-4" /><MessageSquareDashed className="size-4" /><MessageSquarePlus className="size-4" /></div></header><div className="min-h-0 flex-1 space-y-4 overflow-hidden p-4"><div className="ml-auto max-w-[85%] rounded-2xl rounded-tr-sm bg-foreground px-3 py-2 text-background">{lang === "en" ? "Summarize today’s captures." : "整理一下今天的记录。"}</div><div className="max-w-[90%] rounded-2xl rounded-tl-sm bg-muted px-3 py-2 leading-4"><div className="mb-2 flex items-center gap-1 font-medium"><Sparkles className="size-3" />{lang === "en" ? "Summary" : "今日摘要"}</div>{lang === "en" ? "You recorded three product ideas, one meeting memo, and two interface references." : "你记录了三个产品想法、一条会议速记和两组界面参考。"}</div></div><div className="m-3 rounded-2xl border p-2"><p className="min-h-9 px-1 text-muted-foreground">{lang === "en" ? "Message NoteGen…" : "给 NoteGen 发送消息……"}</p><div className="flex items-center"><Plus className="size-4 text-muted-foreground" /><span className="ml-auto flex size-7 items-center justify-center rounded-full bg-foreground text-background"><Send className="size-3" /></span></div></div></div>
}

export function NoteGenMobileWriting({ lang = "cn" }: { lang?: NoteGenReplicaLanguage }) {
  return <div className="flex min-h-0 flex-1 flex-col"><header className="flex h-11 items-center border-b px-2"><ChevronLeft className="size-4" /><span className="ml-1 min-w-0 flex-1 truncate text-[10px] font-medium">{lang === "en" ? "Design principles.md" : "设计原则.md"}</span><div className="flex items-center gap-3 text-muted-foreground"><SearchCode className="size-4" /><LayoutList className="size-4" /></div></header><article className="min-h-0 flex-1 overflow-hidden px-5 py-6"><h1 className="text-xl font-bold tracking-tight">{lang === "en" ? "Design for calm writing" : "为安静写作而设计"}</h1><p className="mt-4 text-[10px] leading-5">{lang === "en" ? "A good workspace reduces interruption and lets ideas stay visible." : "一个好的工作区，会减少打扰，让想法始终保持可见。"}</p><h2 className="mt-6 text-sm font-semibold">{lang === "en" ? "Capture first" : "先记录"}</h2><p className="mt-2 text-[10px] leading-5 text-muted-foreground">{lang === "en" ? "Structure can wait until it becomes useful." : "结构可以等到真正有用时再出现。"}</p></article></div>
}

export function NoteGenMobileCanvas({ lang = "cn" }: { lang?: NoteGenReplicaLanguage }) {
  return <div className="flex min-h-0 flex-1 flex-col"><header className="flex h-11 items-center border-b px-2"><span className="flex size-8 items-center justify-center rounded-full bg-muted"><User className="size-4" /></span><div className="ml-auto flex items-center gap-3 text-muted-foreground"><FilePlus2 className="size-4" /><EllipsisVertical className="size-4" /></div></header><div className="grid min-h-0 flex-1 grid-cols-2 content-start gap-3 overflow-hidden p-4">{[[lang === "en" ? "Product map" : "产品地图", "8"], [lang === "en" ? "Research" : "调研资料", "12"], [lang === "en" ? "Launch plan" : "发布计划", "6"]].map(([title, count]) => <article key={title} className="rounded-xl border bg-card p-2"><div className="relative aspect-[4/3] rounded-lg bg-[radial-gradient(circle_at_center,var(--border)_1px,transparent_1px)] [background-size:8px_8px]"><span className="absolute left-2 top-3 h-5 w-9 rounded border bg-background" /><span className="absolute bottom-2 right-2 h-6 w-10 rounded border bg-muted" /></div><h3 className="mt-2 truncate font-medium">{title}</h3><p className="text-[7px] text-muted-foreground">{count} {lang === "en" ? "nodes" : "个节点"}</p></article>)}</div></div>
}

export function NoteGenMobileSettings({ lang = "cn" }: { lang?: NoteGenReplicaLanguage }) {
  const groups = [
    { label: lang === "en" ? "Basic" : "基础设置", items: [[Settings, lang === "en" ? "General Settings" : "常规设置"], [PenTool, lang === "en" ? "Record Settings" : "记录设置"], [FileCog, lang === "en" ? "Editor Settings" : "编辑器设置"], [Palette, lang === "en" ? "Canvas Settings" : "画布设置"], [ScanText, lang === "en" ? "Image Recognition" : "图像识别"], [Volume2, lang === "en" ? "Audio Settings" : "语音设置"]] },
    { label: lang === "en" ? "AI & Extensions" : "AI 与扩展", items: [[Bot, lang === "en" ? "Model Services" : "模型服务"], [Globe2, lang === "en" ? "Web Search" : "网络搜索"], [BookOpen, lang === "en" ? "Knowledge Base" : "知识库"], [Brain, lang === "en" ? "Memory Management" : "记忆管理"], [Drama, lang === "en" ? "Prompt" : "提示词"], [Puzzle, "MCP"], [Sparkles, lang === "en" ? "Skills" : "技能"], [LayoutTemplate, lang === "en" ? "Template" : "整理模板"]] },
    { label: lang === "en" ? "Data & Storage" : "数据与存储", items: [[DatabaseBackup, lang === "en" ? "Sync" : "同步配置"], [ImageUp, lang === "en" ? "Image Storage" : "图片存储"], [FolderOpen, lang === "en" ? "File Settings" : "文件管理"]] },
  ] as const
  const levels = [0, 1, 0, 2, 3, 0, 1, 1, 2, 3, 2, 0, 1, 0, 0, 1, 2, 3, 2, 1, 0, 1, 0, 2, 3, 3, 2, 0]
  return <div className="min-h-0 flex-1 overflow-hidden px-3 py-3"><div className="flex flex-col gap-3"><div className="rounded-[1.1rem] border bg-muted/20 p-3"><div className="flex items-start gap-3"><span className="flex size-11 items-center justify-center rounded-full border bg-muted"><Cloud className="size-5" /></span><div className="min-w-0 flex-1"><div className="text-xs font-semibold">{lang === "en" ? "Sync platform" : "同步平台"}</div><div className="mt-2 flex gap-1"><span className="rounded-full border px-2 py-0.5 text-[7px]">{lang === "en" ? "Local only" : "仅本地"}</span><span className="rounded-full border px-2 py-0.5 text-[7px]">{lang === "en" ? "Not configured" : "未配置"}</span></div></div></div></div><section className="rounded-[1.1rem] border bg-muted/20 p-3"><div className="flex items-center"><div><h3 className="text-xs font-semibold">{lang === "en" ? "Activity" : "写作活动"}</h3><p className="mt-1 text-[7px] text-muted-foreground">{lang === "en" ? "The last 16 weeks" : "最近 16 周"}</p></div><RefreshCw className="ml-auto size-3.5 text-muted-foreground" /></div><div className="mt-3 grid grid-flow-col grid-rows-7 gap-1">{levels.map((level, index) => <span key={index} className={cn("aspect-square rounded-[2px]", level === 0 ? "bg-muted" : level === 1 ? "bg-primary/20" : level === 2 ? "bg-primary/45" : "bg-primary/75")} />)}</div></section><div className="grid grid-cols-2 gap-2"><div className="rounded-xl border bg-muted/20 p-3"><p className="text-[7px] text-muted-foreground">{lang === "en" ? "This week" : "本周活动"}</p><p className="mt-1 text-lg font-semibold">12</p></div><div className="rounded-xl border bg-muted/20 p-3"><p className="text-[7px] text-muted-foreground">{lang === "en" ? "Current streak" : "连续记录"}</p><p className="mt-1 text-lg font-semibold">5</p></div></div><section><h3 className="text-xs font-semibold">{lang === "en" ? "Settings" : "设置"}</h3><div className="mt-2 flex h-8 items-center gap-2 rounded-lg border px-2 text-muted-foreground"><Search className="size-3.5" /><span>{lang === "en" ? "Search settings..." : "搜索设置..."}</span></div><div className="mt-1 flex flex-col">{groups[0].items.slice(0, 3).map(([Icon, label]) => <div key={label} className="flex h-8 items-center gap-2 rounded-lg px-1 text-[9px]"><Icon className="size-3.5 text-muted-foreground" /><span>{label}</span><ChevronRight className="ml-auto size-3 text-muted-foreground" /></div>)}</div></section></div></div>
}

export function NoteGenMobileReplica({ lang = "cn", screen = "capture" }: { lang?: NoteGenReplicaLanguage; screen?: NoteGenMobileScreen }) {
  return <NoteGenMobileFrame><div className="flex h-full min-h-0 flex-col"><NoteGenMobileStatusBar />{screen === "capture" ? <NoteGenMobileCapture lang={lang} /> : screen === "chat" ? <NoteGenMobileChat lang={lang} /> : screen === "writing" ? <NoteGenMobileWriting lang={lang} /> : screen === "canvas" ? <NoteGenMobileCanvas lang={lang} /> : <NoteGenMobileSettings lang={lang} />}<NoteGenMobileDock screen={screen} lang={lang} /></div></NoteGenMobileFrame>
}
