import { settingsScrollbarCss } from "@/components/notegen/settings-scrollbar"
import { ChevronDown, FolderOpen, Sparkles, Trash, Upload } from "lucide-react"
import type { NoteGenReplicaLanguage } from "@/components/notegen/types"

export type NoteGenInstalledSkill = { name: string; description: string; enabled?: boolean }

/** Fixed display data. No installation, directory access or deletion. */
export function NoteGenSkillsSettings({ lang = "cn", projectSkills = [], globalSkills = [] }: {
  lang?: NoteGenReplicaLanguage
  projectSkills?: NoteGenInstalledSkill[]
  globalSkills?: NoteGenInstalledSkill[]
}) {
  const en = lang === "en"
  return <div className="ng-skills-settings-content ng-settings-scroll">
    <style>{skillsSettingsCss}</style>
    <header><h2><Sparkles size={24} />{en ? "Skills" : "技能"}</h2><p>{en ? "Skills are reusable AI capability packages that let the assistant apply task-specific behavior." : "技能是可重用的 AI 能力包，让 AI 助手能够根据任务自动应用特定的行为模式。"}</p></header>
    {([{ scope: "project", skills: projectSkills, title: en ? "Workspace skills" : "工作区技能", help: en ? "Installed in this workspace’s skills directory; available only here." : "安装到当前工作区的 skills 目录，仅供当前工作区使用。" }, { scope: "global", skills: globalSkills, title: en ? "Installed global skills" : "已安装的全局技能", help: en ? "Installed in NoteGen’s global Skills directory; available in all workspaces." : "安装到 NoteGen 的全局 Skills 目录，可供所有工作区使用。" }] as const).map(group => <section key={group.scope} data-skills-scope={group.scope}>
      <div className="ng-skills-settings-section-head"><div><h3>{group.title} ({group.skills.length})</h3><p>{group.help}</p></div><div className="ng-skills-settings-actions"><span><FolderOpen size={14} />{en ? "Open directory" : "打开目录"}</span><span><Upload size={14} />{en ? "Install skill" : "安装技能"}<ChevronDown size={14} /></span></div></div>
      {group.skills.length ? <div className="ng-skills-settings-list">{group.skills.map(skill => <article key={skill.name} data-installed-skill={skill.name}><Sparkles size={16} /><div><h4>{skill.name}</h4><p>{skill.description}</p></div><span className="ng-skills-enabled" role="switch" aria-checked={skill.enabled !== false} aria-label={`${en ? "Enable" : "启用"}: ${skill.name}`} data-enabled={skill.enabled !== false}><i /></span><Trash size={16} className="ng-skills-delete" /></article>)}</div> : <div className="ng-skills-settings-empty"><span><Sparkles size={20} /></span><strong>{group.scope === "project" ? (en ? "No skills in this workspace" : "工作区中没有技能") : (en ? "No installed global skills" : "没有已安装的全局技能")}</strong><p>{en ? "Create a SKILL.md file in the skills folder to add a skill." : "在 skills 文件夹中创建 SKILL.md 文件来添加技能"}</p></div>}
    </section>)}
  </div>
}

export const skillsSettingsCss = settingsScrollbarCss + `
.ng-skills-settings-content{height:100%;overflow:auto;padding:32px 64px;color:var(--color-foreground,#18181b);font:14px/1.5 ui-sans-serif,system-ui,-apple-system,"PingFang SC",sans-serif}.ng-skills-settings-content>header{margin:0 0 36px}.ng-skills-settings-content h2{display:flex;align-items:center;gap:8px;font-size:20px;font-weight:600;margin:0 0 6px}.ng-skills-settings-content h2 svg{color:var(--color-muted-foreground,#71717a)}.ng-skills-settings-content p{font-size:14px;color:var(--color-muted-foreground,#71717a);margin:0}.ng-skills-settings-content>section{margin:0 0 24px}.ng-skills-settings-section-head{display:flex;justify-content:space-between;align-items:flex-start;gap:16px;margin-bottom:12px}.ng-skills-settings-section-head h3{font-size:16px;font-weight:600;margin:0 0 4px}.ng-skills-settings-actions{display:flex;gap:8px;flex-shrink:0}.ng-skills-settings-actions>span{height:28px;border:1px solid var(--color-border,#e4e4e7);border-radius:8px;display:flex;align-items:center;gap:5px;padding:0 8px;font-size:12px;font-weight:500;white-space:nowrap}.ng-skills-settings-empty{border:1px dashed var(--color-border,#e4e4e7);border-radius:12px;min-height:146px;display:flex;flex-direction:column;align-items:center;justify-content:center;gap:12px;text-align:center;padding:24px}.ng-skills-settings-empty>span{width:32px;height:32px;border-radius:10px;background:var(--color-muted,#f4f4f5);display:flex;align-items:center;justify-content:center}.ng-skills-settings-empty strong{font-size:14px;font-weight:500}.ng-skills-settings-list{display:flex;flex-direction:column;gap:8px}.ng-skills-settings-list>article{display:flex;align-items:center;gap:12px;padding:12px;border:1px solid var(--color-border,#e4e4e7);border-radius:10px}.ng-skills-settings-list>article>svg:first-child{align-self:flex-start;color:var(--color-muted-foreground,#71717a);margin-top:3px;flex-shrink:0}.ng-skills-settings-list>article>div{flex:1;min-width:0}.ng-skills-settings-list h4{font-size:14px;font-weight:600;margin:0 0 4px}.ng-skills-settings-list p{font-size:14px;line-height:1.5}.ng-skills-enabled{display:inline-flex;align-items:center;width:32px;height:18px;border-radius:20px;flex-shrink:0;padding:2px;background:var(--color-muted,#f4f4f5)}.ng-skills-enabled i{width:14px;height:14px;border-radius:50%;background:var(--color-background,#fff)}.ng-skills-enabled[data-enabled="true"]{justify-content:flex-end;background:var(--color-primary,#18181b)}.ng-skills-enabled[data-enabled="true"] i{background:var(--color-primary-foreground,#fafafa)}.ng-skills-delete{flex-shrink:0;color:#ff5555}
.ng-skills-dialog-backdrop{position:absolute;inset:0;background:rgb(0 0 0/.3);backdrop-filter:blur(5px);display:flex;align-items:center;justify-content:center}.ng-skills-dialog{position:relative;width:1260px;height:660px;border:1px solid var(--color-border,#e4e4e7);border-radius:14px;background:var(--color-background,#fff);overflow:hidden;box-shadow:0 20px 50px #0003}.ng-skills-dialog-close{position:absolute;top:12px;right:12px;width:24px;height:24px;display:flex;align-items:center;justify-content:center;border:0;background:transparent;color:var(--color-foreground,#18181b)}.ng-skills-dialog [data-notegen-replica="settings-shell"]{display:flex;height:100%;width:100%;background:var(--color-background,#fff)}.ng-skills-dialog [data-notegen-replica="settings-shell"]>main{flex:1;min-width:0;height:100%;overflow:hidden}.ng-skills-dialog [data-notegen-replica="settings-shell"]>aside{width:224px;height:100%;flex-shrink:0;display:flex;flex-direction:column;border-right:1px solid var(--color-border,#e4e4e7);padding:16px 0;background:var(--color-muted,#f4f4f5)}.ng-skills-dialog aside>div:first-of-type{padding:0 12px}.ng-skills-dialog aside label{display:flex;gap:8px;height:32px;align-items:center;border:1px solid var(--color-border,#e4e4e7);border-radius:10px;padding:0 8px;color:var(--color-muted-foreground,#71717a)}.ng-skills-dialog aside input{width:100%;min-width:0;border:0;background:transparent;color:var(--color-foreground,#18181b);font-size:14px;outline:none}.ng-skills-dialog aside nav{flex:1;overflow-y:auto;min-height:0;padding:0 12px}.ng-skills-dialog aside nav>div{display:flex;flex-direction:column;gap:2px}.ng-skills-dialog aside nav>div>div{padding:20px 10px 4px;font-size:11px;color:var(--color-muted-foreground,#71717a)}.ng-skills-dialog aside nav button{display:flex;align-items:center;gap:6px;height:32px;min-height:32px;width:100%;padding:0 10px;text-align:left;white-space:nowrap;font-size:14px;font-weight:500;border:0;border-radius:6px;background:transparent;color:var(--color-muted-foreground,#71717a)}.ng-skills-dialog aside nav button[aria-current="page"]{background:var(--color-background,#fff);color:var(--color-foreground,#18181b)}.ng-skills-dialog aside svg{width:16px;height:16px;flex-shrink:0}
.ng-skills-dialog [data-notegen-replica="settings-page"]{display:flex;flex-direction:column;height:100%;font-size:14px}.ng-skills-dialog [data-notegen-replica="settings-page"]>header{padding:32px 64px 24px}.ng-skills-dialog [data-notegen-replica="settings-page"]>header h2{display:flex;align-items:center;gap:8px;font-size:20px;font-weight:600}.ng-skills-dialog [data-notegen-replica="settings-page"]>header svg{width:24px;height:24px}.ng-skills-dialog [data-notegen-replica="settings-page"]>header p{margin-top:6px;color:var(--color-muted-foreground)}.ng-skills-dialog [data-notegen-replica="settings-page"]>div{flex:1;overflow:auto;padding:8px 64px 32px}.ng-skills-dialog [data-notegen-replica="settings-page"]>div>div{display:flex;flex-direction:column;gap:24px}.ng-skills-dialog [data-notegen-replica="settings-section"]{display:flex;flex-direction:column;gap:12px}.ng-skills-dialog [data-notegen-replica="settings-section"] h3{font-size:16px;font-weight:600}.ng-skills-dialog [data-notegen-replica="settings-section"]>div{display:flex;flex-direction:column;gap:12px}.ng-skills-dialog [data-notegen-replica="settings-row"]{display:flex;align-items:center;gap:10px;padding:12px;border:1px solid var(--color-border);border-radius:8px}.ng-skills-dialog [data-notegen-replica="settings-row"]>span{flex-shrink:0;color:var(--color-muted-foreground)}.ng-skills-dialog [data-notegen-replica="settings-row"]>span svg{width:16px;height:16px}.ng-skills-dialog [data-notegen-replica="settings-row"]>div:nth-child(2){flex:1}.ng-skills-dialog [data-notegen-replica="settings-row"]>div:nth-child(2)>div+div{margin-top:4px;color:var(--color-muted-foreground)}.ng-skills-dialog [data-notegen-replica="settings-row"]>div:last-child>span{display:inline-flex;align-items:center;gap:6px;font-size:12px}.ng-skills-dialog [data-notegen-replica="settings-row"]>div:last-child svg{width:14px;height:14px}.ng-skills-dialog [data-notegen-replica="settings-section"] article{padding:16px}.ng-skills-dialog [data-notegen-replica="settings-section"] article>div:first-child{display:flex;gap:12px}.ng-skills-dialog [data-notegen-replica="settings-section"] article>div:first-child>span{padding:8px;align-self:flex-start}.ng-skills-dialog [data-notegen-replica="settings-section"] article>div:last-child{display:flex;justify-content:flex-end;margin-top:12px}.ng-skills-dialog [data-notegen-replica="settings-section"] article h4{font-weight:600}.ng-skills-dialog [data-notegen-replica="settings-section"] article p{color:var(--color-muted-foreground);margin-top:4px}
`
